import { CardTransactionInterface } from "../interfaces/card-transaction";

export const transactionsDraft: CardTransactionInterface[] = [
  {
    id: 1,
    type: "income",
    description: "Salario - Enero",
    amount: 5000.0,
    date: "2024-01-15",
    category: "Salario",
    account: "Cuenta Corriente",
    accountType: "bank",
  },
  {
    id: 2,
    type: "expense",
    description: "Supermercado Walmart",
    amount: 156.5,
    date: "2024-01-14",
    category: "Alimentación",
    account: "Tarjeta de Crédito",
    accountType: "credit",
  },
  {
    id: 3,
    type: "expense",
    description: "Gasolina Shell",
    amount: 45.0,
    date: "2024-01-12",
    category: "Transporte",
    account: "Efectivo",
    accountType: "cash",
  },
  {
    id: 4,
    type: "income",
    description: "Freelance - Diseño Web",
    amount: 800.0,
    date: "2024-01-10",
    category: "Freelance",
    account: "Cuenta de Ahorros",
    accountType: "savings",
  },
  {
    id: 5,
    type: "expense",
    description: "Netflix Suscripción",
    amount: 15.99,
    date: "2024-01-08",
    category: "Entretenimiento",
    account: "Tarjeta de Débito",
    accountType: "debit",
  },
  {
    id: 6,
    type: "expense",
    description: "Pago préstamo - Banco Nacional",
    amount: 750.0,
    date: "2024-01-20",
    category: "Préstamos",
    account: "Cuenta Corriente",
    accountType: "bank",
  },
  {
    id: 7,
    type: "income",
    description: "Pago recibido - María González",
    amount: 500.0,
    date: "2024-01-18",
    category: "Préstamos",
    account: "Cuenta de Ahorros",
    accountType: "savings",
  },
]